name: Run Video Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # repo එකට file write කිරීමට අවසර

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "yt-dlp[default,curl-cffi]" curl-cffi telethon requests

      - name: Run Bot Script
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
        run: python runner.py

      - name: Commit & Push updated queue.json
        if: always() # Script එක ඉවර වුණ ගමන් කෝමහරි push වෙනවා
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add queue.json
          git commit -m "Update queue.json progress [skip ci]" || echo "No changes to commit"
          git push
